branches:
  only:
    - master
language: ruby
rvm:
  - 1.9.3
before_script: 
    # Unpack ssh key for git
  - echo -n $id_rsa_{00..23} >> ~/.ssh/id_rsa_base64
  - base64 --decode --ignore-garbage ~/.ssh/id_rsa_base64 > ~/.ssh/id_rsa-yttrium
  - chmod 600 ~/.ssh/id_rsa-yttrium
  # Disable SSH server fingerprint verification
  - echo -e "Host yttrium\n\tStrictHostKeyChecking no\n\tHostName 178.79.165.98\n" >> ~/.ssh/config
script: 
  - bundle exec rake generate
  - bundle exec rake deploy
env:
  global:
    - secure: "YoWUUNL+xffdUn3IGv4APqIa57Z4P7+jXSADwjX7Gx61NZOrXDTlxpXTeFULGp4nf6gzYotXfa3h/hxcHaNjfMDd60Tdd1n3EutDb2f9pE1zW2J0ril5ddSAMyRx/TewvSbMOjm9BFbeBoyqELCfIPNnI1rLgFz1l362zqxuIG8="
    - secure: "bGe6m7+cPOSiKv2ZyS16XzriZFYYBGiqHcif9Nmwc7QwjdoQp5Tvlpy/VCVR/nIGMNOQG5gY62nSAj8FoJAXiLZpAZYYWiM3FeDh7WD84tpmVp2YgKg9GuXnGuFhEIzVB7p1Gleu1opE2x4/xrPijrBMkLegHtx/68pZO1ZExsM="
    - secure: "h+M99PzbnIg1PiDEp4Fe8jUJEbnibGSAm7Ep9yzeCrvMSA16o5c69HiKCHKSVy87UosGhxcpoRcFchXR6dVS70nnm68Q8lwrXpKr9wnfG/2ZVqQEahcJMKYfbycKGIvXEZxGVgexgCLfmzXakmY61s3Re3uY+Ea4buKaGI30kh0="
    - secure: "IiedyFEi+L8ZOM+5kHHYsU7f0CrKU95Tq/4BCBQV+FIMsM2q/lGt3QXrZxSfGUJIrIBcmghXhpeg0rP8LL6+ar94m5Aks4TeiXVJnidiEkI5IbNDpA5nhX2GoSE3+MI2RtKzRSSBC6zDAL9sKXkF91Ds28Dvj1LmXVEo23xVeNw="
    - secure: "eG/7rGonNZy8wD6XXo/dG4VWmadSJyoBH1e3sqSKI0qeA3uicmt5FWkvjIqQRVoKSLJqbIRzrXmSaLmqrKXybHic1GyRsBiNZ/QoPST3qRd2cXfqRhKgd0bQxtbC8E2+KO+iFR7mtYE53LrfQjgLd5LhIOoNB2jD9KN3J0v3ioU="
    - secure: "iXwxPaoxkPLqiRLJP+CATPDJG5N1i4CN93xgK1rtyKLc9LNzIG1kcxbcqvmqWdXJtnTa0o7vejJ6qkRIWrT9nZtqqhOggAqlZlYsfm+nPtN0JT1QU9Zeq7FOBH9xInIGV+g8JTN70Re+uTzO4d2ywu52PvsDdQxjBz0Dhqz9h+0="
    - secure: "Xy80dbU7kNb9E4bO6o3dHEZPnp6xD3Qi6KZKA1frfUGhYEwwChq+tKsGRMU4ghZwnNzo8CENOnkAppC+RStcch1VkS0ZVX2+nq150PaZxlyaviHeK2edQFtuHzfE9eGyQSSgzsKw2XlxGd/Q4iBmJZ56HEwE1QbAJXVGmnMSBG0="
    - secure: "A8/UOQkycY9iga6CYzxN+pVBlZU7ig+3/xBvBQ8NAvBdq+2T4Fd9JbEtcW/zF1v60i0YdrcsXgOjooIp7eLD8AlBg+GXviW7Fb2W48S6iaXdYPxAWEmGYsJwx1gDM/7RaznyBVwSwFHdTJ2cE9PWhlT/TSobnRUnwZFCoplHeHc="
    - secure: "DOTFItpKDtxsaVcVQZ6SAX4ZijEQgPwH9v69ZCfkZkVFp8otgAUgfckKBlUi95U/8acCKbP36CEQdyio1E3LFkG//mHUexI0L49g2O+/nyRu82iP3Ah/wKqRJCl0+tLjIWYmmLua3WOwChHRhW2XaT95FJZvEni1tfxJT/dsMLs="
    - secure: "aY9+rowiyONPUIptPlMH6Ym/3bK02XYqbS+u3P1hiHNV8+hRIEkhWXS6YTtPTxQm4NQg38u5IO3rD0Qp+in+cB22wFVQNlb3d5ZHUN7uZJ+yKiNwc1ZKTjJnlwKbC4oKXa3Au8wmnNp88GpJyzEuVte50Jyvi0MNv4x6CiyFBp4="
    - secure: "hPN9yW2jizUT8srxncmbm/5aNsWouCdH3nd/HuNW/5FmjHbXmzZc4RWUwNn4IFp7YDkgURYlvcxMAHCRHc4+jRmKm2FMByZvUn70V8RlFjXj6QWKp011nDrddc6rOQ3k0AE44Dtuvgb4Jsq8xklna27reFl2bxdYrGpsjuj7wu8="
    - secure: "SqW6bC7ieFRZL5hqqwYXmr1RHxUJOS0id04DpoLrZRQqPgllDT7jR44v/Vx3JfZh8FgfOVS7wD3C35JE5x405NPRIFXrJ8Q/ut4nLq8ZIFyfA4dTDUsszspAHOUy/uIIgiXu9pgpdn2puxQ8kq2hPGi5d3xizwGqb3KkCwv3Sq4="
    - secure: "C9UYe+CBCMPS6WqfHAK/yaGdEpWALt+jVop2a5+7ExyKT2ZPSsTR+u72biJwZSLggurS0KZK2rLkxGIVYL1CiTpZj1MvaMJw5R3L1CVI70j7su/skgeK3p/In2Or0/RGAE14si0Q/IpwyaxRzsEHEW0xkpmlm/oWspI8mCH2/6Q="
    - secure: "H3nVfoiJ6g5SKwjHV0HE1ecydM36PXvp8Vx08xPh8zOAphZUQ4tCppV+W4fOgm8c6J3zqwOWkXVRCZ3RWNUxNMnMZjB6PRdKPm5APZisgwwpVXC03Vu46GrFZV1y8Lvb6p+Ef2kSNkj0t0XXHkbxE8O7GUvFFlMsg2zOTqwmUjY="
    - secure: "E7IZYEEsrSCS9GxAVcPXUaoaNEbLSfpdLD0Dh5UBil0IwhSNZ+WBHuCUB16ezFdcrQQ6816a79uV8y6Yrjnfz5Hr7Tvo6gDtPZ/5vojyfpVyPhXRlZtIMc08NVUoCu3tX5NZ58pPzCzhYEcBJ49Kvwu62Kzz2EKE74aTih5wleQ="
    - secure: "Sg5Fx31VU4xHYP+cTAQkFDpsOH4zxOWZjkhfxCFBfqd2Y5dpZ0KZcjt23+eTaWEkXgAufdQv2755+inlMHEBmYF5nUYpP+NLSTtiWhWbYxrtPVsVORvju0GKHo3kmxDNm1TYyyGd9i0bZ8BU5zbZL4WgfXbX2AX8YN/IvUnti50="
    - secure: "Mmxe9zoh571alvKCU/UbH3Bv1SJ3DYGmQG9VPjYXh77YQ0zwhuoFznylkZxufq7ufpW/MfiQWXgpYyguFbZI1+E4HhKrrba3mxtDNrxfoD7Gwf8RuE/3Z3nCdoL2aWSSySz/UY06TV2UakxnOyqoQsb1t5LH/gJWDfCmzXOjD80="
    - secure: "bzhtILRtIfUgqpx804EBJsTxzaqkC7hA7N26uSqiXMm2mOoPliYx/5oBqIzijYd7gXnDhuVvA8sk0hTKKbgmQ8djnNSaGJDWtzPcM01YHgbdOJDMkd9oHWeqsJYciWU1RHw8Zkb33EOjm7HJHKVpvRcpOVTzyrKyhNNZErnH2gg="
    - secure: "d2U+GYKRvSEQi/EKN+s2rLc7DNa4ZE2nHhFkxPIBbmChuS9AYRMIqR1dLuZYDfJc7j1zytMORqmpwyQYnt9F1z4rXY8QRC8nZeT83MW8I2zHkzYRRZOWyheHS9yKIK1xZU5f2wXb4RBfZa7XSio8ufSpezkZAoqCf2NxwU6xiCY="
    - secure: "U3s0hUzWzFErQs4z3j+MIU2o0lr80Zbm62aywH07km+lkI6TRx7c06FF1PYDJuUJTx/WWSMP+IlVYA5OiF3U9jvNv/QEV6NIndVSQguT6kEHyTcsA2TZoriFDNTlWhbkraeAlkd7ZKPLor6udt99YMU1pAq80pJ4/L4F+EkKvmQ="
    - secure: "INvlM/sOXZ8DXqcpOgnma0lM5jVf2kK+kPZPVHv6hBB3tMlpqk6AKb756qV32+2RCNbBnhs/VZrlwm367ABz/hpaQscpEF4B7to3b2cUlckqPWASgNaH5XuoUUsWp58QGt5j5VeMPUJ3qCKhvh7zSxhI5xnyrjOwP/CwPo0kflU="
    - secure: "abUKKdQOgXc3j7M01XHZ1YxjgD+1h2SQYf8fEKcJtbAGU4NuIFSlWiEPk8xKcETIBusg5JFFRnfRbiTXpkA0xZCjoaNqYeXn4XqcA4aInu2L+Gba18DFPgPh3G9GFE6ZfBo11EjkpPI5pTbgK/rblaSOklrHpu51xgGRfwNcUus="
    - secure: "LxRcfBZJ4omU/s1aziRW6Vp42olgDRbSyR7fh0/9zbNBLE8HAMe5CeLbD1zXm+Efau7M072yrRGQRVeLt9i4skfxIHx6mI3cIkfRj+NSBmXaJUej8urkHBM6xxjypt5ERlop/7feCf3BMZFgj4ul++X5Cxsm1ODrsgZ5xJaJT94="
