# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://rvgn.org
title: Reasonable Vegan
subtitle: Evidence-based compassion for the modern world
author: RVGN
description: Evidence-based compassion for the modern world
fixed_navigation: true

# Default date format is "ordinal" (resulting in "July 22nd 2007")
# You can customize the format as defined in
# http://www.ruby-doc.org/core-1.9.2/Time.html#method-i-strftime
# Additionally, %o will give you the ordinal representation of the day
date_format: "%A %o of %B"

# RSS / Email (optional) subscription links (change if using something like Feedburner)
subscribe_rss: /atom.xml
subscribe_email:
# RSS feeds can list your email address if you like
email: feedback@rvgn.io

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# If publishing to a subdirectory as in http://site.com/project set 'root: /project'
root: /
permalink: /:year/:month/:day/:title/
source: source
destination: public
plugins: plugins
code_dir: downloads/code
category_dir: category
markdown: rdiscount
rdiscount:
  extensions:
    - autolink
    - footnotes
    - smart
highlighter: pygments # default python pygments have been replaced by pygments.rb

paginate: 10          # Posts per page on the blog index
paginate_path: "/posts/:num"  # Directory base for pagination URLs eg. /posts/2/
recent_posts: 4       # Posts in the sidebar Recent Posts section
excerpt_link: "Read on &rarr;"  # "Continue reading" link text at the bottom of excerpted articles
excerpt_separator: "<!--more-->"

# list each of the sidebar modules you want to include, in the order you want them to appear.
# To add custom asides, create files in /source/_includes/custom/asides/ and add them to the list like 'custom/asides/custom_aside_name.html'
default_asides: [asides/recent_posts.html, asides/github.html, asides/delicious.html, asides/pinboard.html, asides/googleplus.html]

# Each layout uses the default asides, but they can have their own asides instead. Simply uncomment the lines below
# and add an array with the asides you want to use.
# blog_index_asides:
# post_asides:
# page_asides:

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# Github repositories
github_user:
github_repo_count: 0
github_show_profile_link: true
github_skip_forks: true

# Twitter
twitter_user:
twitter_tweet_button: true

# Google +1
google_plus_one: false
google_plus_one_size: medium

# Google Plus Profile
# Hidden: No visible button, just add author information to search results
googleplus_user:
googleplus_hidden: false

# Pinboard
pinboard_user:
pinboard_count: 3

# Delicious
delicious_user:
delicious_count: 3

# Disqus Comments
disqus_short_name: rvgn
disqus_show_comment_count: true

# Google Analytics
google_analytics_tracking_id:

# Facebook Like
facebook_like: true

# ----------------------- #
#  Links                  #
# ----------------------- #

links:
  - name: "The Abolitionist"
    desc: "An online magazine promoting abolitionism and reason within animal rights."
    link: "http://theabolitionist.info"

  - name: "Skeptical Vegan"
    desc: "A blog featuring detailed skeptical analysis of topics pertinent to veganism which explores the intersections between science, animal rights, and social justice."
    link: "http://skepticalvegan.com"

  - name: "The Vegan RD"
    desc: "Ginny Messina’s blog takes an evidence-based approach to vegan nutrition."
    link: "http://theveganrd.com"

  - name: "Counting Animals"
    desc: "An amazing resource for statistical enquiry into animal use."
    link: "http://countinganimals.com"

  - name: "The Vegan Option"
    desc: "A radio show and blog featuring stories, science, and analysis from vegan perspectives"
    link: "http://theveganoption.org"            

  - name: "Be Vegan Anywhere"
    desc: "Dedicated to normalizing veganism and making it accessible to people from all walks of life and in as many places on the globe as possible."
    link: "http://bevegananywhere.com"

  - name: "Pythagorean Crank"
    desc: "Offers a critical perspective on the vegan movement, exploring and illuminating issues surrounding veganism and the use of animals."
    link: "http://pythagoreancrank.com"

  - name: "Science-Based Medicine"
    desc: "Dedicated to evaluating medical treatments and products of interest to the public in a scientific light, and promoting the highest standards and traditions of science in health care."
    link: "http://sciencebasedmedicine.org"

  - name: "Logical Veganism"
    desc: "A Resource for the Logic of Veganism"
    link: "http://logicalveganism.blogspot.co.uk"

  - name: "Effective Altruism"
    desc: "Promotes an evidence based approach to ‘doing good’ in the world and answering the question: of all the possible ways to make a difference, which will make the most difference?"
    link: "http://effective-altruism.com"    

# ----------------------- #
#  Prose.io Settings      #
# ----------------------- #

prose:
  rooturl: "source/_posts"
  media: 'media'
  metadata:
    "source/_posts":
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "date"
        field:
          element: "hidden"
      - name: "title"
        field:
          element: "text"
          value: "Title"
      - name: "author"
        field:
          label: "Author"
          element: "text"
          value: "RVGN"          
      - name: "categories"
        field:
          element: "select"
          label: "Category"
          value: "science"
          options:
            - name: "Science"
              value: "science"
            - name: "Current affairs"
              value: "current affairs"
            - name: "Optinion"
              value: "opinion"              
      - name: "tags"
        field:
          element: "multiselect"
          label: "tags"
          alterable: true
          options:
            - name: "Science"
              value: "science"
      - name: "comments"
        field:
          label: "Allow comments"
          element: "checkbox"
          value: true
      - name: "published"
        field:
          label: "Published"
          element: "checkbox"
          value: false
